### ISSUE TITLE
请问为什么需要WRITE_ONCE这个在list.h里面的宏？

### ISSUE THREAD

**Issue by torchlegend** [calvinwilliams/tcplstat#4]
您好，我最近在读您的源文件。在其中发现了一个宏
这个宏
 #define WRITE_ONCE(_var_,_val_)		(_var_) = (_val_)
就是一个单纯的让_val_赋值给_var_
我看您在INIT_LIST_HEAD这个函数中创建头结点的时候，用WRITE_ONCE这个宏来让list->next = list， 却在下一步直接list->prev = list；
是有什么深意吗？

**Comment by calvinwilliams** [comment]
没深意。这个list实现是从Linux内核中提取出来的 ^_^
